INSERT INTO estado (nome, abreviacao) VALUES ('Rondônia', 'RO');
INSERT INTO estado (nome, abreviacao) VALUES ('Acre', 'AC');
INSERT INTO estado (nome, abreviacao) VALUES ('Amazonas', 'AM');
INSERT INTO estado (nome, abreviacao) VALUES ('Roraima', 'RR');
INSERT INTO estado (nome, abreviacao) VALUES ('Pará', 'PA');
INSERT INTO estado (nome, abreviacao) VALUES ('Amapá', 'AP');
INSERT INTO estado (nome, abreviacao) VALUES ('Tocantins', 'TO');
INSERT INTO estado (nome, abreviacao) VALUES ('Maranhão', 'MA');
INSERT INTO estado (nome, abreviacao) VALUES ('Piauí', 'PI');
INSERT INTO estado (nome, abreviacao) VALUES ('Ceará', 'CE');
INSERT INTO estado (nome, abreviacao) VALUES ('Rio Grande do Norte', 'RN');
INSERT INTO estado (nome, abreviacao) VALUES ('Paraíba', 'PB');
INSERT INTO estado (nome, abreviacao) VALUES ('Pernambuco', 'PE');
INSERT INTO estado (nome, abreviacao) VALUES ('Alagoas', 'AL');
INSERT INTO estado (nome, abreviacao) VALUES ('Sergipe', 'SE');
INSERT INTO estado (nome, abreviacao) VALUES ('Bahia', 'BA');
INSERT INTO estado (nome, abreviacao) VALUES ('Minas Gerais', 'MG');
INSERT INTO estado (nome, abreviacao) VALUES ('Espírito Santo', 'ES');
INSERT INTO estado (nome, abreviacao) VALUES ('Rio de Janeiro', 'RJ');
INSERT INTO estado (nome, abreviacao) VALUES ('São Paulo', 'SP');
INSERT INTO estado (nome, abreviacao) VALUES ('Paraná', 'PR');
INSERT INTO estado (nome, abreviacao) VALUES ('Santa Catarina', 'SC');
INSERT INTO estado (nome, abreviacao) VALUES ('Rio Grande do Sul', 'RS');
INSERT INTO estado (nome, abreviacao) VALUES ('Mato Grosso do Sul', 'MS');
INSERT INTO estado (nome, abreviacao) VALUES ('Mato Grosso', 'MT');
INSERT INTO estado (nome, abreviacao) VALUES ('Goiás', 'GO');
INSERT INTO estado (nome, abreviacao) VALUES ('Distrito Federal', 'DF');